version: "3"
# https://docs.docker.com/compose/compose-file/
# support Docker version 17.05.0-ce
services:

#################################### gitlab ######################################################

##############################
# mshk_gitlab
##############################
  mshk_gitlab:
    image: idoall/gitlab-ce:11.4.6-ce.0
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    networks:
      - mshk
    deploy:
      replicas: 1
      update_config:
        delay: 1s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
        reservations:
          cpus: '0.25'
          memory: 1024M


# 统一网络设置
networks:
  mshk:
    driver: overlay
