version: '2'
services:
  walle-web-db:
    image: "mysql:5.7"
    ports:
     - "6033:3306"
    # expose:
    #   - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=walle
    volumes:
       - ./walle-web-db:/home/work/_app/mysql/data/
  walle-web:
    image: "idoall/walle-web"
    build: 
        context: .
        dockerfile: Dockerfile
    ports:
     - "80:80"
    links:
     - walle-web-db:mysql
    depends_on:
     - walle-web-db
  #   - postgres
  # volumes:
  #   - ./app/src:/usr/share/nginx/html
  #   # Your php.ini
  #   - /home/config/php.ini:/usr/local/etc/php/php.ini:ro
  # environment:
    # Set your APP env variables here:
    # - APP_KEY=
    # - DB_HOST=
    # - DB_DATABASE=
    # - DB_USERNAME=
    # - DB_PASSWORD=
    # 
    # 