version: '3'
services:
  web:
    image: "idoall/walle-web:1.6.2"
    ports:
      - "80:80"
      - "2222:22"
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  mysql:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=walle-web
    ports:
      - 3306:3306
    deploy:
      restart_policy:
        condition: on-failure